sgp4: Patch source to make it compile with libc++
Summary:
asinh is part of math.h since C99 times, there's no need to define it
ourselves.

```
Fixes compilation with Clang:
.../marble/src/3rdparty/sgp4/sgp4ext.cpp:210:9:
error: 'asinh' is missing exception specification 'throw()'
double  asinh
        ^
.../marble/src/3rdparty/sgp4/sgp4ext.h:65:9: note:
previous declaration is here
double  asinh
        ^
```

Reviewers: #marble, nienhueser

Reviewed By: #marble, nienhueser

Subscribers: nienhueser

Differential Revision: https://phabricator.kde.org/D3708