define QT_NO_VERSION_TAGGING
Since libastro doesn't link to Qt libraries, in order to not keep
an undefined reference to qt_version_tag in libastro,
QT_NO_VERSION_TAGGING has to be defined