Fixing build error
error: conversion from 'QHash<int, QPair<double, double> >::iterator' to non-scalar type 'QHash<int, QPair<double, double> >::const_iterator' requested

REVIEW: 126310
(cherry picked from commit 479c754faa99553536626aff1859c7d04e1fe6e8)